Hassan
-------
NAKIVO meeting (#291716)
Nakivo x Basan - Demo #292538

Alex
-----
curl --request POST \
    --url https://74.199.244.190:31001/c/login \
    --cookie @cookies.txt \
    --data '{
        "tid": 1}'

{
  "action": "JobSummaryManagement",
  "method": "getJobInfo",
  "tid": "1",
  "type": "rpc",
  "message": null,
  "where": null,
  "cause": null,
  "data": {
    "children": [
      {
        "name": "Backup job for VMware",
        "id": 3,
        "vid": "JOB-3",
        "hvType": "VMWARE",
        "hvTypeBackupCount": {
          "VMWARE": 1
        },
        "hvTypeBackupHasRootDiskCount": {

        },
        "status": "GREEN",
        "jobType": "BACKUP",
        "added": "2024-05-09T15:54:54.092+07:00",
        "updated": "2024-05-09T15:54:54.092+07:00",
        "vmCount": 1,
        "vmTemplateCount": 0,
        "diskCount": 1,
        "jobSameTypeCount": 3,
        "sourcesSize": 32768,
        "sourcesAllocatedSize": 32768,
        "isEnabled": true,
        "isLicensed": true,
        "isEdited": false,
        "isLocked": false,
        "isLockedRunningJob": false,
        "isRemoved": false,
        "fromBackup": false,
        "reachedTerminalLimitState": false,
        "averageDurationMs": 18590,
        "averageDurationSampleCount": 1,
        "crState": "WAITING_SCHEDULE",
        "crDate": null,
        "crDateRelative": 0,
        "crVmPlanned": 0,
        "crVmOk": 0,
        "crVmFailed": 0,
        "crVmSkipped": 0,
        "crVmStopped": 0,
        "crProgress": 0,
        "crTotalProcessedItem": 0,
        "crTotalNewProcessedItem": 0,
        "crAdhoc": false,
        "crSiteRecoveryRunType": null,
        "crRecoveryTimeObjectiveType": null,
        "crRecoveryTimeObjective": null,
        "crFailoverType": null,
        "hasLastRun": true,
        "lrState": "OK",
        "lrDate": "2024-05-09T16:51:01.563+07:00",
        "lrFinishDate": "2024-05-09T16:51:20.153+07:00",
        "lrSpeed": 0,
        "lrDurationMs": 18590,
        "lrDataKb": 0,
        "lrVmOk": 1,
        "lrVmFailed": 0,
        "lrVmSkipped": 0,
        "lrVmStopped": 0,
        "lrAdhoc": false,
        "lrCompressionRatio": 0,
        "lrSiteRecoveryRunType": null,
        "lrRecoveryTimeObjectiveType": null,
        "lrRecoveryTimeObjective": null,
        "lrFailoverType": null,
        "lrActionFailed": 0,
        "lrActionSkipped": 0,
        "lrActionSucceed": 0,
        "lrActionStopped": 0,
        "lrJobPriority": 5,
        "lrSkippedItems": null,
        "differentialTrackingMode": "NONE",
        "preScriptExecutionMode": "NEVER",
        "preScriptBehavior": "NONE",
        "preScriptErrorMode": "NONE",
        "preScriptPath": null,
        "postScriptExecutionMode": "NEVER",
        "postScriptBehavior": "NONE",
        "postScriptErrorMode": "NONE",
        "postScriptPath": null,
        "thinDiskMode": "AUTO",
        "ebsVolumeMode": "AUTO",
        "temporaryVolumeType": "MAGNETIC",
        "networkAccelerationMode": "NONE",
        "encryptionMode": "NONE",
        "applicationAwareMode": "NONE",
        "applicationAwareAgentMode": null,
        "retentionPolicy": null,
        "powerVmsOn": false,
        "generateMac": false,
        "recoveryType": null,
        "powerSourceVmsOff": false,
        "sendReports": false,
        "transporterMode": "AUTO",
        "targetLocationType": null,
        "exchangeLogTruncationMode": "NONE",
        "sqlLogTruncationMode": "NONE",
        "vmVerificationType": "NONE",
        "fullBackupRunSettingsType": "ALWAYS",
        "fullBackupMode": "ACTIVE",
        "runFullOnPreFullFailed": null,
        "recoveryTimeObjectiveType": null,
        "recoveryTimeObjective": null,
        "tapeAppending": null,
        "targetStorageType": "DISK",
        "objects": [
          {
            "vid": "JOB_OBJECT-6",
            "lrStepVid": "JOB_EXECUTION_STEP-18",
            "lrState": "SUCCEEDED",
            "lrSpeed": 0,
            "lrDataTransferredUncompressed": 0,
            "lrDuration": 10,
            "lrTotalDuration": 17490,
            "lrBackupType": "FULL",
            "lrBandwidthLimit": 0,
            "lrTransporterModes": [
              "LAN"
            ],
            "lrLogicalSteps": [
              {
                "id": 131,
                "step": "INIT",
                "state": "SUCCEEDED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": "2024-05-09T16:51:02.569+07:00",
                "finished": "2024-05-09T16:51:04.083+07:00",
                "duration": 1514,
                "runCount": 1,
                "processedProgress": null,
                "maxProgress": null,
                "startedJobExecutionStep": "2024-05-09T16:51:02.570+07:00",
                "finishedJobExecutionStep": "2024-05-09T16:51:20.044+07:00",
                "stateJobExecutionStep": "SUCCEEDED",
                "durationJobExecutionStep": 17474
              },
              {
                "id": 132,
                "step": "WAIT_FOR_TRANSPORTER",
                "state": "SUCCEEDED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": "2024-05-09T16:51:04.087+07:00",
                "finished": "2024-05-09T16:51:04.204+07:00",
                "duration": 117,
                "runCount": 1,
                "processedProgress": null,
                "maxProgress": null,
                "startedJobExecutionStep": null,
                "finishedJobExecutionStep": null,
                "stateJobExecutionStep": null,
                "durationJobExecutionStep": null
              },
              {
                "id": 133,
                "step": "BANDWIDTH_ALLOCATION",
                "state": "SKIPPED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": "2024-05-09T16:51:04.205+07:00",
                "finished": "2024-05-09T16:51:04.208+07:00",
                "duration": 3,
                "runCount": 1,
                "processedProgress": null,
                "maxProgress": null,
                "startedJobExecutionStep": null,
                "finishedJobExecutionStep": null,
                "stateJobExecutionStep": null,
                "durationJobExecutionStep": null
              },
              {
                "id": 134,
                "step": "REMOVING_OLD_SNAPSHOTS",
                "state": "SKIPPED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": "2024-05-09T16:51:04.210+07:00",
                "finished": "2024-05-09T16:51:04.215+07:00",
                "duration": 5,
                "runCount": 1,
                "processedProgress": null,
                "maxProgress": null,
                "startedJobExecutionStep": null,
                "finishedJobExecutionStep": null,
                "stateJobExecutionStep": null,
                "durationJobExecutionStep": null
              },
              {
                "id": 135,
                "step": "DATA_TRANSFER",
                "state": "SUCCEEDED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": "2024-05-09T16:51:04.217+07:00",
                "finished": "2024-05-09T16:51:20.024+07:00",
                "duration": 15807,
                "runCount": 1,
                "processedProgress": 7751,
                "maxProgress": 7751,
                "startedJobExecutionStep": null,
                "finishedJobExecutionStep": null,
                "stateJobExecutionStep": null,
                "durationJobExecutionStep": null
              },
              {
                "id": 136,
                "step": "EXCHANGE_LOGS_TRUNCATION",
                "state": "SKIPPED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": "2024-05-09T16:51:20.026+07:00",
                "finished": "2024-05-09T16:51:20.028+07:00",
                "duration": 2,
                "runCount": 1,
                "processedProgress": null,
                "maxProgress": null,
                "startedJobExecutionStep": null,
                "finishedJobExecutionStep": null,
                "stateJobExecutionStep": null,
                "durationJobExecutionStep": null
              },
              {
                "id": 137,
                "step": "SQL_SERVER_LOGS_TRUNCATION",
                "state": "SKIPPED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": "2024-05-09T16:51:20.030+07:00",
                "finished": "2024-05-09T16:51:20.032+07:00",
                "duration": 2,
                "runCount": 1,
                "processedProgress": null,
                "maxProgress": null,
                "startedJobExecutionStep": null,
                "finishedJobExecutionStep": null,
                "stateJobExecutionStep": null,
                "durationJobExecutionStep": null
              },
              {
                "id": 138,
                "step": "APPLY_RETENTION_POLICY",
                "state": "SUCCEEDED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": "2024-05-09T16:51:20.035+07:00",
                "finished": "2024-05-09T16:51:20.037+07:00",
                "duration": 2,
                "runCount": 1,
                "processedProgress": null,
                "maxProgress": null,
                "startedJobExecutionStep": null,
                "finishedJobExecutionStep": null,
                "stateJobExecutionStep": null,
                "durationJobExecutionStep": null
              },
              {
                "id": 139,
                "step": "VM_VERIFICATION",
                "state": "SUCCEEDED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": null,
                "finished": "2024-05-09T16:51:20.077+07:00",
                "duration": null,
                "runCount": 1,
                "processedProgress": null,
                "maxProgress": null,
                "startedJobExecutionStep": null,
                "finishedJobExecutionStep": null,
                "stateJobExecutionStep": null,
                "durationJobExecutionStep": null
              },
              {
                "id": 140,
                "step": "COMPLETE",
                "state": "SUCCEEDED",
                "processedItem": 0,
                "newProcessedItem": 0,
                "started": null,
                "finished": "2024-05-09T16:51:20.077+07:00",
                "duration": null,
                "runCount": 1,
                "processedProgress": null,
                "maxProgress": null,
                "startedJobExecutionStep": null,
                "finishedJobExecutionStep": null,
                "stateJobExecutionStep": null,
                "durationJobExecutionStep": null
              }
            ],
            "crState": "SCHEDULED",
            "crProgress": 10000,
            "crTransporterModes": null,
            "crProcessedItem": 0,
            "crNewProcessedItem": 0,
            "crLogicalSteps": null,
            "backupMethodMode": "NORMAL",
            "crActionName": null,
            "includedInJobRun": false,
            "crSpeed": 0,
            "crDataTransferredUncompressed": 0,
            "crDuration": 0,
            "crTotalDuration": 0,
            "crBandwidthLimit": 0,
            "sourceVid": "VM-36",
            "sourceName": "@a",
            "sourcePowerState": "OFF",
            "sourceSubType": "VM",
            "sourceType": null,
            "targetVid": "BACKUP_OBJECT-6",
            "targetName": "@a",
            "targetPowerState": "UNKNOWN",
            "targetSubType": null,
            "verificationState": null,
            "screenshotName": null,
            "screenshotPath": null,
            "flashBootState": "WAITING",
            "waitingReason": null,
            "waitingFor": null,
            "waitingForVid": null,
            "remainWaitingTime": null,
            "hasCompletedSavepoint": false,
            "lastFullFailed": false,
            "crRpoValue": 0,
            "rpoType": null,
            "jobExecutionStepState": null
          }
        ],
        "transporters": [
          {
            "isAuto": true,
            "usedAsSource": false,
            "usedAsTarget": false,
            "usedAsProxy": false,
            "maxLoadFactor": 0,
            "currentTotalLoad": 0,
            "vid": null,
            "name": null,
            "state": null
          },
          {
            "isAuto": false,
            "usedAsSource": false,
            "usedAsTarget": true,
            "usedAsProxy": false,
            "maxLoadFactor": 6,
            "currentTotalLoad": 0,
            "vid": "TRANSPORTER-1",
            "name": "Onboard transporter",
            "state": "OK"
          }
        ],
        "storages": [
          {
            "vid": "BACKUP_REPOSITORY-1",
            "name": "Onboard repository",
            "size": 21275807744,
            "free": 12417695744,
            "used": 144880898,
            "state": "OK",
            "online": true,
            "infiniteSize": false,
            "type": "INCREMENTAL_WITH_FULL_BACKUPS",
            "location": "LOCAL"
          }
        ],
        "actions": [],
        "crActionExecutions": null,
        "lrActionExecutions": null,
        "scheduleRetention": true,
        "useBackupEncryption": false,
        "isChangedEncryption": false,
        "schedules": [
          {
            "id": 4,
            "uuid": null,
            "name": null,
            "enabled": true,
            "type": null,
            "monthlyEveryType": "SECOND",
            "everyType": "MINUTE",
            "every": 1,
            "startTime": "04:51:00 PM",
            "endTime": null,
            "dayOfWeek": 4,
            "dayOfMonth": 1,
            "month": 0,
            "timezone": "Asia/Bangkok",
            "on": 31,
            "triggerItem": null,
            "triggerItemSchedule": null,
            "triggerRunType": null,
            "triggerEvents": null,
            "nextRun": "2024-06-13T16:51:00.000+07:00",
            "referenceTime": null,
            "effectiveDate": null,
            "position": 1,
            "triggerItemName": null,
            "triggerItemTypeName": null,
            "timezoneOffsetMs": 25200000,
            "nextRunRelative": 3023968727,
            "scheduleRetentionType": "MONTHLY",
            "customKeepSavepointCount": 6,
            "customKeepSavepointType": "MONTHS",
            "keepImmutableSavepointCount": null,
            "copyOneLatestOnly": null
          },
          {
            "id": 5,
            "uuid": null,
            "name": "",
            "enabled": true,
            "type": null,
            "monthlyEveryType": "LAST",
            "everyType": "MINUTE",
            "every": 1,
            "startTime": "04:51:00 PM",
            "endTime": null,
            "dayOfWeek": 5,
            "dayOfMonth": 1,
            "month": 0,
            "timezone": "Asia/Bangkok",
            "on": 31,
            "triggerItem": null,
            "triggerItemSchedule": null,
            "triggerRunType": null,
            "triggerEvents": null,
            "nextRun": "2024-05-10T16:51:00.000+07:00",
            "referenceTime": null,
            "effectiveDate": null,
            "position": 2,
            "triggerItemName": null,
            "triggerItemTypeName": null,
            "timezoneOffsetMs": 25200000,
            "nextRunRelative": 86368727,
            "scheduleRetentionType": "WEEKLY",
            "customKeepSavepointCount": 10,
            "customKeepSavepointType": "DAYS",
            "keepImmutableSavepointCount": null,
            "copyOneLatestOnly": false
          }
        ],
        "lockReasons": []
      }
    ],
    "totalCount": 1
  }
}
