curl --request POST \
    --url https://74.199.244.190:31001/c/login \
    --cookie @cookies.txt \
    --data '{
        "method": "getJobInfo",
        "data": [[1],0],
        "type": "rpc",
        "tid": 1}'
